[package]
name = "cypher-tests"
version = "0.1.0"
authors = ["Alexandre RICCIARDI <alexandre.ricciardi@pm.me>"]
edition = "2018"

[lib]
name = "cypher_tests"

[dependencies]
one-graph-server = { path = "../../lib/one-graph-server" }
one-graph-core = { path = "../../lib/one-graph-core" }
one-graph-client = { path = "../../client/one-graph-client" }
log = "0.4"
simple_logger = "1.11.0"
tokio = { version = "1.13.0", features = ["full"] }