[workspace]
members = [
    "lib/zawgl-core",
    "lib/zawgl-query-planner",
    "lib/zawgl-tx-handler",
    "lib/zawgl-cypher",
    "lib/zawgl-gremlin",
    "lib/zawgl-server",
    "zawgl",
    "utils",
    "client/zawgl-client",
    "integration/cypher-tests",
]