[workspace]
members = [
    "lib/zawgl-core",
    "lib/zawgl-front",
    "lib/zawgl-cypher-query-model",
    "lib/zawgl-server",
    "zawgl",
    "utils",
    "client/zawgl-client",
    "integration/cypher-tests",
]