[workspace]
members = [
    "lib/one-graph-core",
    "lib/one-graph-tx-handler",
    "lib/one-graph-cypher",
    "lib/one-graph-gremlin",
    "lib/one-graph-server",
    "og",
    "utils",
    "one-graph-client",
]