[package]
name = "zawgl"
version = "0.1.3"
authors = ["Alexandre RICCIARDI <alexandre.ricciardi@pm.me>"]
edition = "2021"

[dependencies]
zawgl-core = { path = "../lib/zawgl-core" }
zawgl-server = { path = "../lib/zawgl-server" }
tokio-tungstenite = "*"
tokio = { version = "1.13.0", features = ["full"] }
tungstenite = "*"
futures-util = "0.3.8"
log = "0.4"
config = "0.13.2"
serde = {version = "1.0", features = ["derive"] }
simple_logger = "4.1.0"
toml = "0.7.4"