[package]
name = "zawgl-utils"
version = "0.1.1"
authors = ["Alexandre RICCIARDI <aricciardi501@gmail.com>"]
edition = "2021"

[dependencies]
zawgl-core = { path = "../lib/zawgl-core" }
log = { workspace = true }