name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run integration tests
      run: sh integration/scripts/launch.sh
